services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    volumes:
      - ./configs/config.prod.yml:/app/configs/config.yml
      - ./assets/:/app/assets
